services:
  - type: cron
    name: bse-order-alerts
    env: python
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python main.py
    schedule: "0 11 * * *"
