services:
  - type: cron
    name: bse-order-alerts
    env: python
    buildCommand: |
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt
    startCommand: python3 main.py
    schedule: "0 11 * * *"
