services:
  - type: cron
    name: bse-order-alerts
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: /opt/render/project/venv/bin/python3 main.py
    schedule: "0 11 * * *"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
