services:
  - type: cron
    name: bse_order_alerts_bot
    env: python
    schedule: "0 12 * * *"  # runs every day at 12:00 PM UTC (5:30 PM IST)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
