services:
  - type: cron
    name: bse-order-alerts
    env: python
    buildCommand: |
      pip install requests
      pip install -r requirements.txt
    startCommand: python3 main.py
    schedule: "0 11 * * *"
