services:
  - type: cron
    name: bse-order-alerts-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    schedule: "0 4 * * *"     # Adjust time as needed
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
