services:
  - type: web
    name: bse-order-alerts
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: /opt/render/project/venv/bin/python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
