services:
  - type: cron
    name: bse-order-alerts
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: /opt/render/project/venv/bin/python main.py
    schedule: "0 11 * * *"
